/*
 * dma.c
 *
 *  Created on: 12 Aug 2019
 *      Author: me
 */

#include "dma.h"

void InitDMA(){
	DMA1_1_Init();
	DMA1_23_Init();
	DMA1_4_Init();
}

void DMA1_1_Init(){
	//CHANNEL 1 IS USED FOR SPI1 TX MODE ONLY

	DMA1_Channel1->CCR = 0;				//CLEAR ALL BITS
	DMAMUX1_ChannelStatus->CFR |= 1;	//CLEAR CHANNEL 1 OVERRUN FLAG
	DMA1->IFCR |= (1|2);				//CLEAR CHANNEL 1 INTERUPTS
	DMA1_Channel1->CNDTR = 0;			//SET DATA LEN TO ZERO
	DMA1_Channel1->CPAR = (uint32_t)&SPI1->DR;		//PERIPHERAL ADDRESS TARGET (SPI DATA REGISTER)
	DMA1_Channel1->CCR &= ~2;			//SET BIT 2 TO 0. NO INTERUPT ON TX.
	DMA1_Channel1->CCR |= 16;			//SET BIT 4 TO 1. DIRECTION - MEM TO PERIPH;
	DMA1_Channel1->CCR |= 128;			//SET BIT 8 TO 1. MEM INCREMENT MODE.
	DMA1_Channel1->CCR |= 8192;			//SET 13th > 12th BITS TO 1,0. HIGH PRIORITY MODE (LEV 3/4)

	DMAMUX1_Channel0->CCR = 17;			//SET MUX CHANNEL TO SPI1 TX.
}

void DMA1_23_Init(){
	//CHANNEL 2 IS USED FOR SPI1 RX ONLY
	DMA1_Channel2->CCR = 0;				//CLEAR ALL BITS
	DMAMUX1_ChannelStatus->CFR |= 2;	//CLEAR CHANNEL 2 OVERRUN FLAG
	DMA1->IFCR |= (16|32);				//CLEAR CHANNEL 4 INTERUPTS
	DMA1_Channel2->CNDTR = 0;			//SET DATA LEN TO ZERO
	DMA1_Channel2->CPAR = (uint32_t)&SPI1->DR;					//ADDRESS OF SRC DATA
	DMA1_Channel2->CMAR = (uint32_t)bufferSPI_RX;				//PERIPHERAL ADDRESS SOURCE (SPI DATA REGISTER)
	DMA1_Channel2->CCR |= 2;			//SET BIT 2 TO 1. TRANSFER COMPLETE INTERUPT ENABLED
	DMA1_Channel2->CCR &= ~16;			//SET BIT 4 TO 0. DIRECTION - PERIPH TO MEM;
	DMA1_Channel2->CCR |= 128;			//SET BIT 8 TO 1. MEM INCREMENT MODE.
	DMA1_Channel2->CCR |= 8192;			//SET 13th > 12th BITS TO 1,0. HIGH PRIORITY MODE (LEV 3/4)

	DMAMUX1_Channel1->CCR = 16;			//SET MUX CHANNEL TO SPI1 RX.
}

void DMA1_4_Init(){
	//CHANNEL 4 IS USED FOR SPI 2 TX ONLY (TO PANELS)
	DMA1_Channel4->CCR = 0;				//CLEAR ALL BITS
	DMAMUX1_ChannelStatus->CFR |= 8;	//CLEAR CHANNEL 4 OVERRUN FLAG
	DMA1->IFCR |= (4096|8192);			//CLEAR CHANNEL 4 INTERUPTS
	DMA1_Channel4->CNDTR = 0;			//SET DATA LEN TO ZERO

	DMA1_Channel4->CPAR = (uint32_t)&SPI2->DR;		//PERIPHERAL ADDRESS TARGET (SPI DATA REGISTER)
	DMA1_Channel4->CCR |= 2;			//SET BIT 2 TO 1. TRANSFER COMPLETE INTERUPT ENABLED
	DMA1_Channel4->CCR |= 16;			//SET BIT 4 TO 1. DIRECTION - MEM TO PERIPH;
	DMA1_Channel4->CCR |= 128;			//SET BIT 8 TO 1. MEM INCREMENT MODE.
	DMA1_Channel4->CCR |= 8192;			//SET 13th > 12th BITS TO 1,0. HIGH PRIORITY MODE (LEV 3/4)

	DMAMUX1_Channel3->CCR = 19;			//SET MUX CHANNEL TO SPI2 TX.
}

void DMA1_1_IRQ(){
	printf("CallBack1\n");
	DMA1_Channel1->CCR &= ~2;	//CLEAR TRANSFER COMPLETE FLAG
	DMA1->IFCR |= (1|2);		//CLEAR ALL CHANNEL 1 INTERUPT
	DMA1_Channel1->CCR &= ~1;	//DISABLE DMA
}


void DMA1_23_IRQ(){
	DMA1_Channel2->CCR &= ~2;	//CLEAR TRANSFER COMPLETE FLAG
	DMA1->IFCR |= (16|32);		//CLEAR ALL CHANNEL 2 INTERUPT
	DMA1_Channel2->CCR &= ~1;	//DISABLE DMA
	SPI1RXComplete();
}

void DMA1_47_IRQ(){
	DMA1_Channel4->CCR &= ~2;	//CLEAR TRANSFER COMPLETE FLAG
	DMA1->IFCR |= (4096|8192);	//CLEAR ALL CHANNEL 4 INTERUPT
	DMA1_Channel4->CCR &= ~1;	//DISABLE DMA
	SPI2TXComplete();
}


//RECEIVE FROM PI
void ReceiveSPI1DMA(uint8_t *ptr, uint16_t len){
	//DMA1_Channel2->CCR &= ~769;								//SET BIT 0 TO 0 TO DISABLE DMA. SET BITS 8 and 9 to 0. CLEAR THE PERIPHERAL DATA SIZE. 00 SET US IN 8BIT MODE.
	DMA1_Channel2->CNDTR = len;									//DATA LENGTH OF TRANSFER
	//DMA1_Channel2->CPAR = (uint32_t)&SPI2->DR;				//ADDRESS OF SRC DATA - SET ON INIT
	DMA1_Channel2->CMAR = (uint32_t)ptr;						//PERIPHERAL ADDRESS SOURCE (SPI DATA REGISTER) - SET ON INIT. ALWAYS BUFFER ADDR 0.
	DMA1_Channel2->CCR |= 3;									//SET BIT 0 TO 1 TO ENABLE THE DMA TRANSFER. SET BIT 1 TO 1 TO ENABLE TRANSFER COMPLETE INTERUPT
	//printf("RX Start\n");
}

void TransmitReceiveSPI1DMA(uint8_t *ptrTX, uint8_t *ptrRX, uint16_t len){
	//printf("TXRX\n");
	global.txRXMode = TRUE;
	DMA1_Channel2->CNDTR = len;									//DATA LENGTH OF TRANSFER
	DMA1_Channel1->CNDTR = len;									//DATA LENGTH OF TRANSFER
	DMA1_Channel2->CMAR = (uint32_t)ptrRX;						//PERIPHERAL ADDRESS SOURCE (SPI DATA REGISTER) - SET ON INIT. ALWAYS BUFFER ADDR 0.
	DMA1_Channel1->CMAR = (uint32_t)ptrTX;			//ADDRESS OF SRC DATA

	DMA1_Channel2->CCR |= 3;									//SET BIT 0 TO 1 TO ENABLE THE DMA TRANSFER. SET BIT 1 TO 1 TO ENABLE TRANSFER COMPLETE INTERUPT
	DMA1_Channel1->CCR |= 1;									//SET BIT 0 TO 1 TO ENABLE THE DMA TRANSFER.
}


//TRANSMIT TO PANELS
void TransmitSPI2DMA(uint8_t *ptr, uint16_t len){
	//printf("Send\n");
	//DMA1_Channel4->CCR &= ~769;								//SET BIT 0 TO 0 TO DISABLE DMA. SET BITS 8 and 9 to 0. CLEAR THE PERIPHERAL DATA SIZE. 00 SET US IN 8BIT MODE.
	//DMA1_Channel1->CCR |= 256;									//ENABLE 16 BIT MODE
	DMA1_Channel4->CNDTR = len;									//DATA LENGTH OF TRANSFER
	//DMA1_Channel1->CPAR = (uint32_t)&SPI1->DR;		//PERIPHERAL ADDRESS TARGET (SPI DATA REGISTER) - SET ON INIT
	DMA1_Channel4->CMAR = (uint32_t)ptr;			//ADDRESS OF SRC DATA
	//DMA1->IFCR |= 1;											//FORCE BIT 0 TO A 1 TO CLEAR ALL CHANNEL 1 INTERUPT FLAGS
	DMA1_Channel4->CCR |= 3;									//SET BIT 0 TO 1 TO ENABLE THE DMA TRANSFER. SET BIT 1 TO 1 TO ENABLE TRANSFER COMPLETE INTERUPT
}
